version: "3.8"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: kependudukan
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: userpass
      DB_NAME: kependudukan
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data: